### ISSUE TITLE
Identifier 'Notification' has already been declared

### ISSUE THREAD

**Issue by Ratatinator97** [saidsay-so/nuxt-buefy-purgecss#2]
Hi,
Thanks for this amazing module 😁 !
I'm experiencing a bug where I have duplicate imports.

```sh
ERROR in ./.nuxt/plugins/buefy-loader.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/alex/Documents/PicTalk/pictalk-frontend/.nuxt/plugins/buefy-loader.js: Identifier 'Notification' has already been declared. (25:2)

  23 |   Modal,
  24 |   Toast,
> 25 |   Notification,
     |   ^
  26 |   Dialog
  27 | } from 'buefy';
  28 |
    at Object._raise (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:541:17)
    at Object.raiseWithData (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:534:17)
    at Object.raise (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:495:17)
    at ScopeHandler.checkRedeclarationInScope (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:1688:12)
    at ScopeHandler.declareName (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:1654:12)
    at Object.checkLVal (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:11086:24)
    at Object.parseImportSpecifier (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:15007:10)
    at Object.parseNamedImportSpecifiers (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:14983:36)
    at Object.parseImport (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:14814:39)
    at Object.parseStatementContent (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:13454:27)
    at Object.parseStatement (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:13352:17)
    at Object.parseBlockOrModuleBlockBody (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:13941:25)
    at Object.parseBlockBody (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:13932:10)
    at Object.parseProgram (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:13272:10)
    at Object.parseTopLevel (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:13263:25)
    at Object.parse (/Users/alex/Documents/PicTalk/pictalk-frontend/node_modules/@babel/parser/lib/index.js:15037:10)
 @ ./.nuxt/index.js 56:0-80 490:25-57 496:19-51
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

Here is the `buefy-loader.js`code: 
```js
import Vue from 'vue';
import {
  Image,
  Input,
  Field,
  Message,
  Button,
  Checkbox,
  Switch,
  Select,
  Table,
  Icon,
  Tabs,
  Steps,
  Notification,
  Navbar,
  Tooltip,
  Dropdown,
  Autocomplete,
  Pagination,
  Upload,
  Tag,
  Modal,
  Toast,
  Notification,
  Dialog
} from 'buefy';

import { merge } from 'buefy/src/utils/helpers'
import config, { setOptions } from 'buefy/src/utils/config'
import { registerComponentProgrammatic } from 'buefy/src/utils/plugins'
import ConfigComponent from 'buefy/src/utils/ConfigComponent'

export default () => {
  [
    Image,
    Input,
    Field,
    Message,
    Button,
    Checkbox,
    Switch,
    Select,
    Table,
    Icon,
    Tabs,
    Steps,
    Notification,
    Navbar,
    Tooltip,
    Dropdown,
    Autocomplete,
    Pagination,
    Upload,
    Tag,
    Modal,
    Toast,
    Notification,
    Dialog
  ].forEach((component) => Vue.use(component));

  setOptions(merge(
    config,
    {
      "css": false,
      "materialDesignIcons": true,
      "materialDesignIconsHRef": "https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/css/materialdesignicons.min.css",
      "async": true
},
    true
  ));

  registerComponentProgrammatic(Vue, 'config', ConfigComponent);
};
```

How can I fix that ? I had search in all my project but can't find a duplicate import or thing like that.

Thanks again,
Alex

**Comment by saidsay-so** [comment]
It should be resolved by the version 0.2.2. Let me know if you experience this bug again!
